### ISSUE TITLE
coffee-source.kamelet.yaml not found

### ISSUE THREAD

**Issue by srinivasks22** [apache/camel-kamelets#1508]
I'm new and I'm trying to deploy KameletBinding and I get the below error. Attached the relevent kamelet source and binding file (as.log files)

exec java -cp ./resources:/etc/camel/application.properties:/etc/camel/conf.d/_resources:/etc/camel/conf.d/user.properties:/etc/camel/resources:/etc/camel/sources/camel-k-embedded-flow.yaml:/etc/camel/sources/log-sink.yaml:dependencies/app/camel-k-integration-1.12.0.jar:dependencies/lib/boot/io.github.crac.org-crac-0.1.3.jar:dependencies/lib/boot/io.quarkus.quarkus-bootstrap-runner-2.16.0.Final.jar:dependencies/lib/boot/io.quarkus.quarkus-development-mode-spi-2.16.0.Final.jar:dependencies/lib/boot/io.smallrye.common.smallrye-common-io-1.13.2.jar:dependencies/lib/boot/org.glassfish.jakarta.json-1.1.6.jar:dependencies/lib/boot/org.graalvm.sdk.graal-sdk-22.3.0.jar:dependencies/lib/boot/org.jboss.logging.jboss-logging-3.5.0.Final.jar:dependencies/lib/boot/org.jboss.logmanager.jboss-logmanager-embedded-1.0.11.jar:dependencies/lib/boot/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:dependencies/lib/main/com.fasterxml.jackson.core.jackson-annotations-2.14.1.jar:dependencies/lib/main/com.fasterxml.jackson.core.jackson-core-2.14.1.jar:dependencies/lib/main/com.fasterxml.jackson.core.jackson-databind-2.14.1.jar:dependencies/lib/main/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.14.1.jar:dependencies/lib/main/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.14.1.jar:dependencies/lib/main/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.14.1.jar:dependencies/lib/main/com.fasterxml.jackson.module.jackson-module-parameter-names-2.14.1.jar:dependencies/lib/main/com.github.mifmif.generex-1.0.2.jar:dependencies/lib/main/com.squareup.okhttp3.logging-interceptor-3.14.9.jar:dependencies/lib/main/com.squareup.okhttp3.okhttp-3.14.9.jar:dependencies/lib/main/com.squareup.okio.okio-1.17.2.jar:dependencies/lib/main/dk.brics.automaton.automaton-1.11-8.jar:dependencies/lib/main/io.fabric8.kubernetes-client-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-client-api-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-httpclient-okhttp-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-admissionregistration-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-apiextensions-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-apps-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-autoscaling-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-batch-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-certificates-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-common-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-coordination-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-core-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-discovery-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-events-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-extensions-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-flowcontrol-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-gatewayapi-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-metrics-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-networking-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-node-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-policy-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-rbac-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-scheduling-6.3.1.jar:dependencies/lib/main/io.fabric8.kubernetes-model-storageclass-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-client-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-client-api-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-clusterautoscaling-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-config-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-console-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-hive-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-installer-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-machine-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-machineconfig-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-miscellaneous-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-monitoring-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-operator-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-operatorhub-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-storageversionmigrator-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-tuned-6.3.1.jar:dependencies/lib/main/io.fabric8.openshift-model-whereabouts-6.3.1.jar:dependencies/lib/main/io.fabric8.zjsonpatch-0.3.0.jar:dependencies/lib/main/io.quarkus.arc.arc-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-arc-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-core-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-fs-util-0.0.9.jar:dependencies/lib/main/io.quarkus.quarkus-jackson-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-jsonp-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-kubernetes-client-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-kubernetes-client-internal-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-logging-json-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-security-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-security-runtime-spi-2.16.0.Final.jar:dependencies/lib/main/io.quarkus.security.quarkus-security-1.1.4.Final.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-annotation-1.13.2.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-classloader-1.13.2.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-constraint-1.13.2.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-expression-1.13.2.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-function-1.13.2.jar:dependencies/lib/main/io.smallrye.config.smallrye-config-2.13.1.jar:dependencies/lib/main/io.smallrye.config.smallrye-config-common-2.13.1.jar:dependencies/lib/main/io.smallrye.config.smallrye-config-core-2.13.1.jar:dependencies/lib/main/io.smallrye.config.smallrye-config-source-yaml-2.13.1.jar:dependencies/lib/main/io.smallrye.reactive.mutiny-1.8.0.jar:dependencies/lib/main/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:dependencies/lib/main/jakarta.el.jakarta.el-api-3.0.3.jar:dependencies/lib/main/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:dependencies/lib/main/jakarta.inject.jakarta.inject-api-1.0.jar:dependencies/lib/main/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:dependencies/lib/main/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:dependencies/lib/main/org.apache.camel.camel-api-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-base-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-base-engine-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-bean-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-cloud-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-cluster-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-componentdsl-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-core-catalog-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-core-engine-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-core-languages-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-core-model-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-core-processor-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-core-reifier-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-dsl-support-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-endpointdsl-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-kamelet-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-kubernetes-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-log-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-main-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-management-api-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-microprofile-config-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-support-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-tooling-model-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-util-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-util-json-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-yaml-dsl-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-yaml-dsl-common-3.20.1.jar:dependencies/lib/main/org.apache.camel.camel-yaml-dsl-deserializers-3.20.1.jar:dependencies/lib/main/org.apache.camel.k.camel-k-core-1.17.0.jar:dependencies/lib/main/org.apache.camel.k.camel-k-core-api-1.17.0.jar:dependencies/lib/main/org.apache.camel.k.camel-k-core-support-1.17.0.jar:dependencies/lib/main/org.apache.camel.k.camel-k-runtime-1.17.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-bean-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-core-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-core-cloud-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-kamelet-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-kubernetes-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-log-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-support-bouncycastle-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-support-commons-logging-2.16.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-yaml-dsl-2.16.0.jar:dependencies/lib/main/org.apache.commons.commons-compress-1.22.jar:dependencies/lib/main/org.bouncycastle.bcpkix-jdk15on-1.70.jar:dependencies/lib/main/org.bouncycastle.bcprov-jdk15on-1.70.jar:dependencies/lib/main/org.bouncycastle.bcutil-jdk15on-1.70.jar:dependencies/lib/main/org.eclipse.microprofile.config.microprofile-config-api-2.0.1.jar:dependencies/lib/main/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.2.jar:dependencies/lib/main/org.javassist.javassist-3.26.0-GA.jar:dependencies/lib/main/org.jboss.logging.commons-logging-jboss-logging-1.0.0.Final.jar:dependencies/lib/main/org.jboss.logging.jboss-logging-annotations-2.2.1.Final.jar:dependencies/lib/main/org.jboss.slf4j.slf4j-jboss-logmanager-1.2.0.Final.jar:dependencies/lib/main/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:dependencies/lib/main/org.jboss.threads.jboss-threads-3.4.3.Final.jar:dependencies/lib/main/org.reactivestreams.reactive-streams-1.0.3.jar:dependencies/lib/main/org.slf4j.slf4j-api-1.7.36.jar:dependencies/lib/main/org.snakeyaml.snakeyaml-engine-2.3.jar:dependencies/lib/main/org.yaml.snakeyaml-1.33.jar:dependencies/quarkus-app-dependencies.txt:dependencies/quarkus-run.jar:dependencies/quarkus/generated-bytecode.jar:dependencies/quarkus/quarkus-application.dat io.quarkus.bootstrap.runner.QuarkusEntryPoint
[38;5;145m2023-06-14 19:12:15,187[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.k.Runtime[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mApache Camel K Runtime 1.17.0[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,252[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.qua.cor.CamelBootstrapRecorder[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151m[39mBootstrap runtime: [38;5;188morg.apache.camel.quarkus.main.CamelMainRuntime[39m[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,254[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.mai.MainSupport[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mApache Camel (Main) 3.20.1 is starting[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,355[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.k.lis.SourcesConfigurer[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mLoading routes from: SourceDefinition{name='camel-k-embedded-flow', language='yaml', type='source', location='file:/etc/camel/sources/camel-k-embedded-flow.yaml', }[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,392[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.k.lis.SourcesConfigurer[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mLoading routes from: SourceDefinition{name='log-sink', language='yaml', type='source', location='file:/etc/camel/sources/log-sink.yaml', }[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,776[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69morg.apa.cam.imp.eng.AbstractCamelContext[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mLifecycle strategy org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler@70c0a3d5 vetoed initializing CamelContext (camel-1) due to: Failure creating route from template: coffee-source[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,776[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.imp.eng.AbstractCamelContext[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mCamelContext (camel-1) vetoed to not initialize due to: Failure creating route from template: coffee-source[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,777[39m[38;5;188m [39m[38;5;203mERROR[39m[38;5;188m [[39m[38;5;69morg.apa.cam.qua.mai.CamelMainRuntime[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mFailed to start application[39m[38;5;203m: org.apache.camel.RuntimeCamelException: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: coffee-source
	at org.apache.camel.RuntimeCamelException.wrapRuntimeException(RuntimeCamelException.java:66)
	at org.apache.camel.support.service.BaseService.doFail(BaseService.java:413)
	at org.apache.camel.impl.engine.AbstractCamelContext.doFail(AbstractCamelContext.java:3620)
	at org.apache.camel.support.service.BaseService.fail(BaseService.java:342)
	at org.apache.camel.impl.engine.AbstractCamelContext.failOnStartup(AbstractCamelContext.java:5313)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2691)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2698)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: coffee-source
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.onContextInitialized(KameletComponent.java:433)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:3017)
	at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:174)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2679)
	... 23 more
Caused by: java.io.FileNotFoundException: Resource not found: classpath:/kamelets/coffee-source.kamelet.yaml
	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoaderSupport.doLoadRouteBuilder(YamlRoutesBuilderLoaderSupport.java:76)
	at org.apache.camel.dsl.support.RouteBuilderLoaderSupport.loadRoutesBuilder(RouteBuilderLoaderSupport.java:102)
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:125)
	at org.apache.camel.spi.RoutesLoader.findRoutesBuilders(RoutesLoader.java:120)
	at org.apache.camel.spi.RoutesLoader.loadRoutes(RoutesLoader.java:75)
	at org.apache.camel.support.RouteTemplateHelper.loadRouteTemplateFromLocation(RouteTemplateHelper.java:106)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.createRouteForEndpoint(KameletComponent.java:403)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.onContextInitialized(KameletComponent.java:430)
	... 27 more
[39m[38;5;227m
[39m[38;5;145m2023-06-14 19:12:15,853[39m[38;5;188m [39m[38;5;203mERROR[39m[38;5;188m [[39m[38;5;69mio.qua.run.Application[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mFailed to start application (with profile [prod])[39m[38;5;203m: java.io.FileNotFoundException: Resource not found: classpath:/kamelets/coffee-source.kamelet.yaml
	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoaderSupport.doLoadRouteBuilder(YamlRoutesBuilderLoaderSupport.java:76)
	at org.apache.camel.dsl.support.RouteBuilderLoaderSupport.loadRoutesBuilder(RouteBuilderLoaderSupport.java:102)
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:125)
	at org.apache.camel.spi.RoutesLoader.findRoutesBuilders(RoutesLoader.java:120)
	at org.apache.camel.spi.RoutesLoader.loadRoutes(RoutesLoader.java:75)
	at org.apache.camel.support.RouteTemplateHelper.loadRouteTemplateFromLocation(RouteTemplateHelper.java:106)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.createRouteForEndpoint(KameletComponent.java:403)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.onContextInitialized(KameletComponent.java:430)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:3017)
	at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:174)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2679)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2698)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
[39m[38;5;227m
[39m

[coffee-source.kamelet.log](https://github.com/apache/camel-kamelets/files/11749946/coffee-source.kamelet.log)
[coffee-to-log.log](https://github.com/apache/camel-kamelets/files/11749948/coffee-to-log.log)

oc get kamelets | grep coffee-source        
coffee-source                          Ready

**Comment by oscerd** [comment]
In this repository coffee-source never existed. So I suppose it has something to do with a quickstart or something else.
