### ISSUE TITLE
YAKS tests are constantly failing

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kamelets#792]
@christophd can you please help on this? Thanks a bunch.

**Comment by christophd** [comment]
@oscerd yes, sure

**Comment by christophd** [comment]
I have had a look and it seems to be a problem with the jitpack dependency in version `main-SNAPSHOT`

The `insert-field-action` Kamelet uses `camel-kamelets-utils` library and the Camel K build is not able to download the jar from jitpack repository.

The following error is reported in the operator logs when building the integration kit:
```
{"level":"info","ts":1645817597.18187,"logger":"camel-k.controller.kameletbinding","msg":"Reconciling KameletBinding","request-namespace":"yaks-ac2cf84c-68f3-4b68-8430-88bd7b92dd5d","request-name":"insert-field-test"}
{"level":"info","ts":1645817597.1819808,"logger":"camel-k.controller.kameletbinding","msg":"Invoking action monitor","request-namespace":"yaks-ac2cf84c-68f3-4b68-8430-88bd7b92dd5d","request-name":"insert-field-test","api-version":"camel.apache.org/v1alpha1","kind":"KameletBinding","ns":"yaks-ac2cf84c-68f3-4b68-8430-88bd7b92dd5d","name":"insert-field-test"}
{"level":"info","ts":1645817598.2458668,"logger":"camel-k.maven.build","msg":"The POM for com.github.apache.camel-kamelets:camel-kamelets-utils:jar:main-v0.7.0-g572d488-87 is missing, no dependency information available"}
{"level":"info","ts":1645817598.714263,"logger":"camel-k.controller.build","msg":"Reconciling Build","request-namespace":"openshift-operators","request-name":"kit-c8cispftbnra9v2af12g"}
{"level":"info","ts":1645817598.7145019,"logger":"camel-k.controller.build","msg":"Invoking action monitor-routine","request-namespace":"openshift-operators","request-name":"kit-c8cispftbnra9v2af12g","api-version":"camel.apache.org/v1","kind":"Build","ns":"openshift-operators","name":"kit-c8cispftbnra9v2af12g"}
{"level":"info","ts":1645817599.2198267,"logger":"camel-k.maven.build","msg":"------------------------------------------------------------------------"}
{"level":"info","ts":1645817599.219879,"logger":"camel-k.maven.build","msg":"BUILD FAILURE"}
{"level":"info","ts":1645817599.2198942,"logger":"camel-k.maven.build","msg":"------------------------------------------------------------------------"}
{"level":"info","ts":1645817599.2228167,"logger":"camel-k.maven.build","msg":"Total time:  3.307 s"}
{"level":"info","ts":1645817599.223731,"logger":"camel-k.maven.build","msg":"Finished at: 2022-02-25T19:33:19Z"}
{"level":"info","ts":1645817599.224164,"logger":"camel-k.maven.build","msg":"------------------------------------------------------------------------"}
{"level":"error","ts":1645817599.2255447,"logger":"camel-k.maven.build","msg":"Failed to execute goal on project camel-k-integration: Could not resolve dependencies for project org.apache.camel.k.integration:camel-k-integration:jar:1.7.0: com.github.apache.camel-kamelets:camel-kamelets-utils:jar:main-v0.7.0-g572d488-87 was not found in https://jitpack.io during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jitpack.io-c8cituftbnra9v2af15g has elapsed or updates are forced -> [Help 1]","stacktrace":"github.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:190\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:164\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:123\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:149"}
{"level":"error","ts":1645817599.2264357,"logger":"camel-k.maven.build","msg":"","stacktrace":"github.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:190\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:164\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:123\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:149"}
{"level":"error","ts":1645817599.2268476,"logger":"camel-k.maven.build","msg":"To see the full stack trace of the errors, re-run Maven with the -e switch.","stacktrace":"github.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:190\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:164\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:123\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:149"}
{"level":"error","ts":1645817599.22775,"logger":"camel-k.maven.build","msg":"Re-run Maven using the -X switch to enable full debug logging.","stacktrace":"github.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:190\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:164\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:123\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:149"}
{"level":"error","ts":1645817599.227821,"logger":"camel-k.maven.build","msg":"","stacktrace":"github.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:190\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:164\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:123\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:149"}
{"level":"error","ts":1645817599.2282114,"logger":"camel-k.maven.build","msg":"For more information about the errors and possible solutions, please read the following articles:","stacktrace":"github.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:190\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:164\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:123\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:149"}
{"level":"error","ts":1645817599.2290084,"logger":"camel-k.maven.build","msg":"[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException","stacktrace":"github.com/apache/camel-k/pkg/builder.BuildQuarkusRunnerCommon\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:190\ngithub.com/apache/camel-k/pkg/builder.buildQuarkusRunner\n\tgithub.com/apache/camel-k/pkg/builder/quarkus.go:164\ngithub.com/apache/camel-k/pkg/builder.(*builderStep).execute\n\tgithub.com/apache/camel-k/pkg/builder/steps.go:46\ngithub.com/apache/camel-k/pkg/builder.(*builderTask).Do\n\tgithub.com/apache/camel-k/pkg/builder/builder.go:123\ngithub.com/apache/camel-k/pkg/controller/build.(*monitorRoutineAction).runBuild\n\tgithub.com/apache/camel-k/pkg/controller/build/monitor_routine.go:149"}
{"level":"info","ts":1645817599.2905118,"logger":"camel-k.builder","msg":"step failed with error: failure while building project: exit status 1","step":"github.com/apache/camel-k/pkg/builder/BuildQuarkusRunner","phase":"20","task":"builder"}
{"level":"info","ts":1645817599.2905552,"logger":"camel-k.builder","msg":"dependencies: [camel:core camel:jackson camel:kamelet camel:timer github:apache.camel-kamelets:camel-kamelets-utils:main-SNAPSHOT mvn:org.apache.camel.k:camel-k-knative mvn:org.apache.camel.k:camel-k-knative-producer mvn:org.apache.camel.k:camel-k-runtime mvn:org.apache.camel.quarkus:camel-quarkus-platform-http mvn:org.apache.camel.quarkus:camel-quarkus-yaml-dsl]"}
```

Having a look at the jitpack repository for kamelet-catalog (https://jitpack.io/#apache/camel-kamelets) I can see the Maven build failing for `camel-kamelets-utils` module in main-SNAPSHOT

https://jitpack.io/com/github/apache/camel-kamelets/main-v0.7.0-g572d488-87/build.log

**Comment by christophd** [comment]
I honestly do not know why jitpack resolves `main-SNAPSHOT` to `main-v0.7.0-g572d488-87`

**Comment by oscerd** [comment]
It seems the build is using JDK 8 on jitpack, while it should be using jdk11

**Comment by christophd** [comment]
@oscerd after the JDK version in JitPack has been fixed we get another kind of error in `insert-field-action` test:

```
name=insert-field-action-binding-6cb955d9c7-v48ss
  condition type=Initialized, status=True, reason=, message=""
  condition type=Ready, status=False, reason=ContainersNotReady, message="containers with unready status: [integration]"
  condition type=ContainersReady, status=False, reason=ContainersNotReady, message="containers with unready status: [integration]"
  condition type=PodScheduled, status=True, reason=, message=""
  logs:
    integration
    > 	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
    > 	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
    > 	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
    > 	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
    > 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
    > 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
    > 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:559)
    > 	at io.quarkus.runtime.Application.start(Application.java:101)
    > 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
    > 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
    > 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
    > 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
    > 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    > 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
    > 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
    > [39m[38;5;227m
    > [39m[38;5;145m2022-02-28 09:58:24,070[39m[38;5;188m [39m[38;5;203mERROR[39m[38;5;188m [[39m[38;5;69mio.qua.run.Application[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mFailed to start application (with profile prod)[39m[38;5;203m: java.lang.IllegalArgumentException: Unsupported field: unmarshalType on org.apache.camel.model.dataformat.JsonDataFormat
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.handleUnknownProperty(YamlDeserializerBase.java:110)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:104)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:339)
    > 	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$UnmarshalDefinitionDeserializer.setProperty(ModelDeserializers.java:16685)
    > 	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$UnmarshalDefinitionDeserializer.setProperty(ModelDeserializers.java:16516)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:103)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
    > 	at org.apache.camel.dsl.yaml.deserializers.ProcessorDefinitionDeserializer.construct(ProcessorDefinitionDeserializer.java:36)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:339)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asCollection(YamlDeserializerSupport.java:317)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatCollection(YamlDeserializerSupport.java:298)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatList(YamlDeserializerSupport.java:272)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.setSteps(YamlDeserializerSupport.java:388)
    > 	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$WhenDefinitionDeserializer.setProperty(ModelDeserializers.java:17202)
    > 	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$WhenDefinitionDeserializer.setProperty(ModelDeserializers.java:17156)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:103)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:339)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asCollection(YamlDeserializerSupport.java:317)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatCollection(YamlDeserializerSupport.java:298)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatList(YamlDeserializerSupport.java:272)
    > 	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$ChoiceDefinitionDeserializer.setProperty(ModelDeserializers.java:1534)
    > 	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$ChoiceDefinitionDeserializer.setProperty(ModelDeserializers.java:1498)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:103)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
    > 	at org.apache.camel.dsl.yaml.deserializers.ProcessorDefinitionDeserializer.construct(ProcessorDefinitionDeserializer.java:36)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:339)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asCollection(YamlDeserializerSupport.java:317)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatCollection(YamlDeserializerSupport.java:298)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatList(YamlDeserializerSupport.java:272)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.setSteps(YamlDeserializerSupport.java:388)
    > 	at org.apache.camel.dsl.yaml.deserializers.OutputAwareFromDefinitionDeserializer.setProperties(OutputAwareFromDefinitionDeserializer.java:71)
    > 	at org.apache.camel.dsl.yaml.deserializers.OutputAwareFromDefinitionDeserializer.setProperties(OutputAwareFromDefinitionDeserializer.java:33)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:339)
    > 	at org.apache.camel.dsl.yaml.deserializers.RouteTemplateDefinitionDeserializer.setProperty(RouteTemplateDefinitionDeserializer.java:68)
    > 	at org.apache.camel.dsl.yaml.deserializers.RouteTemplateDefinitionDeserializer.setProperty(RouteTemplateDefinitionDeserializer.java:31)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:103)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
    > 	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
    > 	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configure(YamlRoutesBuilderLoader.java:49)
    > 	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
    > 	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
    > 	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
    > 	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
    > 	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:211)
    > 	at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
    > 	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:550)
    > 	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
    > 	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
    > 	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
    > 	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
    > 	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
    > 	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
    > 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
    > 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
    > 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:559)
    > 	at io.quarkus.runtime.Application.start(Application.java:101)
    > 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
    > 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
    > 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
    > 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
    > 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    > 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
    > 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
```

any idea why this is happening?

**Comment by oscerd** [comment]
I guess it's the camel-k version? https://github.com/apache/camel-kamelets/blob/main/.github/workflows/test.yaml#L44 It should be 1.7.0 at least.

**Comment by christophd** [comment]
@oscerd good call!

**Comment by oscerd** [comment]
The PR for #819 should fix this.
